# .github/dependabot.yml
version: 2
updates:
    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "daily"
      commit-message:
          prefix: feat
          prefix-development: feat
      open-pull-requests-limit: 99
